export const getClient = () => cy.get('#cliente')
export const transactionValue = () => cy.get('#valorTransacao')
export const getMessage = () => cy.get('#alertMessage')
export const getFormActions = () => cy.get('.form-actions')
export const getTitle = () => cy.get('.page-title')